<template>
  <div class="clinic-list">
    <div class="button-box">
      <button>
        <span
          class="q-btn__content text-center col items-center q-anchor--skip justify-center row"
          ><i
            class="q-icon notranslate material-icons"
            aria-hidden="true"
            role="img"
            >chevron_left</i
          ></span
        >
      </button>
      <div class="switching-time">今天</div>
      <button>
        <span
          class="q-btn__content text-center col items-center q-anchor--skip justify-center row"
          ><i
            class="q-icon notranslate material-icons"
            aria-hidden="true"
            role="img"
            >chevron_right</i
          ></span
        >
      </button>
    </div>
    <div class="clinic-list-body">
      <q-table :rows="rows" :columns="columns" row-key="name"> </q-table>
    </div>
  </div>
</template>

<script setup>
const columns = [
  { name: "a", label: "#", field: "a" },
  { name: "b", label: "預約看診日期", field: "b" },
  { name: "c", label: "診次", field: "c" },
  { name: "d", label: "科別", field: "d" },
  { name: "e", label: "診間ID", field: "e" },
  { name: "f", label: "人員姓名", field: "f" },
  { name: "g", label: "預約時間(起)", field: "g" },
  { name: "h", label: "預約時間(迄)", field: "h" },
  { name: "i", label: "診療名稱", field: "i" },
  { name: "j", label: "掛號序號", field: "j" },
  { name: "k", label: "病患姓名", field: "k" },
  { name: "m", label: "生理性別", field: "m" },
];

const rows = [
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
  {
    name: "a",
    a: "0031587",
    b: "2022.10.04 星期二",
    c: "上午診",
    d: "皮膚科",
    e: "001",
    f: "李美麗 醫師",
    g: "na",
    h: "na",
    i: "na",
    j: "1",
    k: "XXX",
    m: "男",
  },
];
</script>

<style lang="scss">
.clinic-list .q-table tbody > tr {
  &:nth-child(odd) {
    background-color: #f2f2f2;
  }
}

.clinic-list .button-box {
  display: flex;

  position: absolute;
  top: 80px;
  right: 28px;

  button {
    background-color: #fff;
    border: 2px solid #ced8e0;
  }

  .switching-time {
    padding: 5px 20px;
    background-color: #ced8e0;
  }
}

.clinic-list .clinic-list-body {
  padding: 10rem 2rem;
}
</style>
